<script src="<?php echo base_url('assets/js/jQuery/jquery.min.js'); ?>"></script>
<script src="<?php echo base_url('assets/js/tetherJs/tether.min.js'); ?>"></script>
<script src="<?php echo base_url('assets/js/materialize/materialize.min.js'); ?>"></script>
<script src="<?php echo base_url('assets/js/chartJs/Chart.bundle.min.js'); ?>"></script>
<script src="<?php echo base_url('assets/js/DataTables/dataTables.min.js'); ?>"></script>
<script src="<?php echo base_url('assets/js/multiForm/multiform.min.js'); ?>"></script>
<script src="<?php echo base_url('assets/js/ryuJs/ryu.js'); ?>"></script>
<script src="<?php echo base_url('assets/js/algorithmJS/algorithmJS.js'); ?>"></script>
<script src="<?php echo base_url('assets/js/mockingJs/index.js'); ?>"></script>
<script src="<?php echo base_url('assets/js/mockingJs/vanilla.js'); ?>"></script>

<script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.6.0/js/dataTables.buttons.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.6.0/js/buttons.flash.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
<script src="https://cdn.datatables.net/buttons/1.6.0/js/buttons.html5.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.6.0/js/buttons.print.min.js"></script>